### ISSUE TITLE
Which SDK 4 versions is this bridge compatible with?

### ISSUE THREAD

**Issue by paulrinaldi** [chaimPaneth/react-native-jw-media-player#344]
The readme states:
"Since version 0.2.0 we use the new JWPlayerKit && SDK 4 check out [iOS get started](https://developer.jwplayer.com/jwplayer/docs/ios-get-started) && [Android get started](https://developer.jwplayer.com/jwplayer/docs/android-get-started)"

Which SDK 4 versions does it use per release? How could I find this out? I'm trying to determine which exoplayer to force require in my project.

**Comment by Jmilham21** [comment]
@paulrinaldi, the bridge is designed to work with the versions below. You can find this definition for Android in the top level [build.gradle](https://github.com/chaimPaneth/react-native-jw-media-player/blob/master/android/build.gradle). For Android/ExoPlayer in the current version of the JW SDK, it's recommended to use `2.18.1` rather than the `2.18.7` that is currently supplied in the bridge's gradle file.

Be aware in the JW Android SDK `4.16.1` or higher, we moved from the now deprecated [ExoPlayer](https://github.com/google/ExoPlayer) library to the new [Media3 ExoPlayer](https://github.com/androidx/media) library. This will cause build failures if you attempt to upgrade to Media3 now.

- Android: `4.15.1`
- iOS: `4.17.0`

**Comment by paulrinaldi** [comment]
I see.

Thank you.

**Comment by paulrinaldi** [comment]
And is the latest `react-native` version that is compatible with this package 0.70?
