### ISSUE TITLE
weird error with react-native 0.62.2

### ISSUE THREAD

**Issue by srinivaassunil** [chaimPaneth/react-native-jw-media-player#72]
I am getting this weird error. Please help
![image](https://user-images.githubusercontent.com/10563463/86436712-6c316100-bd20-11ea-9317-ff505da6ebad.png)

**Comment by chaimPaneth** [comment]
Hi @srinivaassunil can you please check with a previous version of the JW SDK as it might be an issue with a breaking change in the SDK - try to hardcode in the library's build.gradle https://github.com/chaimPaneth/react-native-jw-media-player/blob/master/android/build.gradle instead of `:+` at the end of the implementation definition define a previous SDK number try 3.9.0 for instance.

```
dependencies {
    implementation 'com.facebook.react:react-native:+'
    implementation 'com.longtailvideo.jwplayer:jwplayer-core:+' // <- change to number
    implementation 'com.longtailvideo.jwplayer:jwplayer-common:+' // <- change to number
    implementation 'com.longtailvideo.jwplayer:jwplayer-ima:+' // <- change to number
}

```

**Comment by srinivaassunil** [comment]
Thank you @chaimPaneth. The above solution solved the problem.
